modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/serene-seasons-pams-harvestcraft-2-trees-compat/issues"
[[mods]]
modId = "sereneseasonsphc2trees"
version = "${file.jarVersion}"
displayName = "Serene Seasons - Pam's HarvestCraft 2 - Trees Compat"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/serene-seasons-pams-harvestcraft-2-trees-compat"
logoFile = "sereneseasonsphc2trees.png"
credits = "Thanks for this mod goes to Java and the Forge Team."
authors = "Darkorg"
description = '''Grow your fruit trees in their respective seasons!'''

[[dependencies.sereneseasonsphc2trees]]
modId = "sereneseasons"
mandatory = true
versionRange = "[1.19.2-8.1.0.24,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sereneseasonsphc2trees]]
modId = "pamhc2trees"
mandatory = true
versionRange = "[1.0.1,)"
ordering = "NONE"
side = "BOTH"